; ================================================================================
; Sprite Mappings - generated by Flex 2 Fri Oct 02 2020 12:48:54 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATACJQA1J2E71F:
	dc.w DATACJQA1J2E71F_0-DATACJQA1J2E71F, DATACJQA1J2E71F_1-DATACJQA1J2E71F
	dc.w DATACJQA1J2E71F_2-DATACJQA1J2E71F, DATACJQA1J2E71F_3-DATACJQA1J2E71F
	dc.w DATACJQA1J2E71F_4-DATACJQA1J2E71F, DATACJQA1J2E71F_5-DATACJQA1J2E71F
	dc.w DATACJQA1J2E71F_6-DATACJQA1J2E71F, DATACJQA1J2E71F_7-DATACJQA1J2E71F
	dc.w DATACJQA1J2E71F_8-DATACJQA1J2E71F, DATACJQA1J2E71F_9-DATACJQA1J2E71F
	dc.w DATACJQA1J2E71F_A-DATACJQA1J2E71F, DATACJQA1J2E71F_B-DATACJQA1J2E71F
	dc.w DATACJQA1J2E71F_C-DATACJQA1J2E71F, DATACJQA1J2E71F_D-DATACJQA1J2E71F
	dc.w DATACJQA1J2E71F_E-DATACJQA1J2E71F, DATACJQA1J2E71F_F-DATACJQA1J2E71F
	dc.w DATACJQA1J2E71F_10-DATACJQA1J2E71F, DATACJQA1J2E71F_11-DATACJQA1J2E71F
	dc.w DATACJQA1J2E71F_12-DATACJQA1J2E71F, DATACJQA1J2E71F_13-DATACJQA1J2E71F
	dc.w DATACJQA1J2E71F_14-DATACJQA1J2E71F, DATACJQA1J2E71F_15-DATACJQA1J2E71F
	dc.w DATACJQA1J2E71F_16-DATACJQA1J2E71F, DATACJQA1J2E71F_17-DATACJQA1J2E71F
	dc.w DATACJQA1J2E71F_18-DATACJQA1J2E71F, DATACJQA1J2E71F_19-DATACJQA1J2E71F
	dc.w DATACJQA1J2E71F_1A-DATACJQA1J2E71F, DATACJQA1J2E71F_1B-DATACJQA1J2E71F
	dc.w DATACJQA1J2E71F_1C-DATACJQA1J2E71F, DATACJQA1J2E71F_1D-DATACJQA1J2E71F
	dc.w DATACJQA1J2E71F_1E-DATACJQA1J2E71F, DATACJQA1J2E71F_1F-DATACJQA1J2E71F
	dc.w DATACJQA1J2E71F_20-DATACJQA1J2E71F, DATACJQA1J2E71F_21-DATACJQA1J2E71F
	dc.w DATACJQA1J2E71F_22-DATACJQA1J2E71F, DATACJQA1J2E71F_23-DATACJQA1J2E71F
	dc.w DATACJQA1J2E71F_24-DATACJQA1J2E71F, DATACJQA1J2E71F_25-DATACJQA1J2E71F
	dc.w DATACJQA1J2E71F_26-DATACJQA1J2E71F, DATACJQA1J2E71F_27-DATACJQA1J2E71F
DATACJQA1J2E71F_0: dc.b $0, $4
	dc.b $EC, $F, $0, $0, $0, $0, $FF, $E0
	dc.b $C, $8, $0, $10, $0, $8, $FF, $E8
	dc.b $EC, $F, $8, $0, $8, $0, $0, $0
	dc.b $C, $8, $8, $10, $8, $8, $0, $0
DATACJQA1J2E71F_1: dc.b $0, $2
	dc.b $F8, $5, $0, $13, $0, $9, $FF, $F0
	dc.b $F8, $5, $0, $13, $0, $9, $0, $0
DATACJQA1J2E71F_2: dc.b $0, $4
	dc.b $EC, $9, $0, $17, $0, $B, $FF, $EC
	dc.b $EC, $6, $0, $1D, $0, $E, $0, $4
	dc.b $FC, $6, $0, $23, $0, $11, $FF, $EC
	dc.b $4, $9, $0, $29, $0, $14, $FF, $FC
DATACJQA1J2E71F_3: dc.b $0, $2
	dc.b $F0, $B, $0, $2F, $0, $17, $FF, $E8
	dc.b $F0, $B, $8, $2F, $8, $17, $0, $0
DATACJQA1J2E71F_4: dc.b $0, $1
	dc.b $F0, $F, $0, $3B, $0, $1D, $FF, $F0
DATACJQA1J2E71F_5: dc.b $0, $2
	dc.b $E8, $E, $0, $4B, $0, $25, $FF, $F0
	dc.b $0, $E, $10, $4B, $10, $25, $FF, $F0
DATACJQA1J2E71F_6: dc.b $0, $2
	dc.b $F4, $6, $0, $57, $0, $2B, $FF, $F0
	dc.b $F4, $6, $8, $57, $8, $2B, $0, $0
DATACJQA1J2E71F_7: dc.b $0, $4
	dc.b $F8, $8, $0, $5D, $0, $2E, $FF, $F0
	dc.b $F0, $9, $0, $60, $0, $30, $0, $8
	dc.b $0, $D, $0, $66, $0, $33, $FF, $E0
	dc.b $0, $D, $8, $66, $8, $33, $0, $0
DATACJQA1J2E71F_8: dc.b $0, $1
	dc.b $F8, $5, $0, $6E, $0, $37, $FF, $F8
DATACJQA1J2E71F_9: dc.b $0, $1
	dc.b $F8, $5, $0, $72, $0, $39, $FF, $F8
DATACJQA1J2E71F_A: dc.b $0, $1
	dc.b $FC, $0, $0, $76, $0, $3B, $FF, $FC
DATACJQA1J2E71F_B: dc.b $0, $1
	dc.b $FC, $0, $0, $77, $0, $3B, $FF, $FC
DATACJQA1J2E71F_C: dc.b $0, $1
	dc.b $FC, $0, $0, $78, $0, $3C, $FF, $FC
DATACJQA1J2E71F_D: dc.b $0, $1
	dc.b $FC, $0, $0, $79, $0, $3C, $FF, $FC
DATACJQA1J2E71F_E: dc.b $0, $1
	dc.b $FC, $0, $0, $7A, $0, $3D, $FF, $FC
DATACJQA1J2E71F_F: dc.b $0, $1
	dc.b $FC, $0, $0, $7B, $0, $3D, $FF, $FC
DATACJQA1J2E71F_10: dc.b $0, $1
	dc.b $FC, $0, $0, $7C, $0, $3E, $FF, $FC
DATACJQA1J2E71F_11: dc.b $0, $1
	dc.b $FC, $0, $0, $7D, $0, $3E, $FF, $FC
DATACJQA1J2E71F_12: dc.b $0, $1
	dc.b $F8, $5, $0, $7E, $0, $3F, $FF, $F8
DATACJQA1J2E71F_13: dc.b $0, $1
	dc.b $F8, $5, $0, $82, $0, $41, $FF, $F8
DATACJQA1J2E71F_14: dc.b $0, $1
	dc.b $F8, $5, $0, $86, $0, $43, $FF, $F8
DATACJQA1J2E71F_15: dc.b $0, $1
	dc.b $F8, $5, $0, $8A, $0, $45, $FF, $F8
DATACJQA1J2E71F_16: dc.b $0, $1
	dc.b $FC, $0, $0, $8E, $0, $47, $FF, $FC
DATACJQA1J2E71F_17: dc.b $0, $1
	dc.b $F8, $5, $0, $8F, $0, $47, $FF, $F8
DATACJQA1J2E71F_18: dc.b $0, $1
	dc.b $F8, $5, $0, $93, $0, $49, $FF, $F8
DATACJQA1J2E71F_19: dc.b $0, $1
	dc.b $F4, $A, $0, $97, $0, $4B, $FF, $F4
DATACJQA1J2E71F_1A: dc.b $0, $5
	dc.b $F0, $1, $0, $0, $0, $0, $FF, $E8
	dc.b $F0, $5, $0, $2, $0, $1, $FF, $F8
	dc.b $F0, $1, $8, $0, $8, $0, $0, $10
	dc.b $0, $D, $0, $6, $0, $3, $FF, $E0
	dc.b $0, $D, $8, $6, $8, $3, $0, $0
DATACJQA1J2E71F_1B: dc.b $0, $A
	dc.b $D0, $F, $0, $E, $0, $7, $FF, $D8
	dc.b $D0, $F, $0, $1E, $0, $F, $FF, $F8
	dc.b $F0, $F, $0, $2E, $0, $17, $FF, $D8
	dc.b $F0, $F, $10, $1E, $10, $F, $FF, $F8
	dc.b $10, $F, $10, $E, $10, $7, $FF, $D8
	dc.b $10, $F, $0, $3E, $0, $1F, $FF, $F8
	dc.b $D0, $2, $0, $4E, $0, $27, $0, $18
	dc.b $E8, $6, $0, $51, $0, $28, $0, $18
	dc.b $0, $6, $0, $57, $0, $2B, $0, $18
	dc.b $18, $6, $10, $51, $10, $28, $0, $18
DATACJQA1J2E71F_1C: dc.b $0, $1
	dc.b $F4, $A, $0, $5D, $0, $2E, $FF, $F4
DATACJQA1J2E71F_1D: dc.b $0, $1
	dc.b $F4, $A, $0, $66, $0, $33, $FF, $F4
DATACJQA1J2E71F_1E: dc.b $0, $2
	dc.b $F0, $7, $0, $0, $0, $0, $FF, $F0
	dc.b $F0, $7, $8, $0, $8, $0, $0, $0
DATACJQA1J2E71F_1F: dc.b $0, $2
	dc.b $F4, $A, $0, $8, $0, $4, $FF, $E8
	dc.b $F4, $A, $8, $8, $8, $4, $0, $0
DATACJQA1J2E71F_20: dc.b $0, $2
	dc.b $F8, $D, $0, $11, $0, $8, $FF, $E0
	dc.b $F8, $D, $0, $19, $0, $C, $0, $0
DATACJQA1J2E71F_21: dc.b $0, $2
	dc.b $F0, $7, $0, $21, $0, $10, $FF, $F8
	dc.b $10, $4, $0, $29, $0, $14, $FF, $F8
DATACJQA1J2E71F_22: dc.b $0, $2
	dc.b $F0, $F, $0, $2B, $0, $15, $FF, $F0
	dc.b $10, $C, $0, $3B, $0, $1D, $FF, $F0
DATACJQA1J2E71F_23: dc.b $0, $1
	dc.b $F8, $5, $8, $7E, $8, $3F, $FF, $F8
DATACJQA1J2E71F_24: dc.b $0, $1
	dc.b $F8, $5, $18, $86, $18, $43, $FF, $F8
DATACJQA1J2E71F_25: dc.b $0, $1
	dc.b $F6, $A, $8, $5D, $8, $2E, $FF, $F5
DATACJQA1J2E71F_26: dc.b $0, $1
	dc.b $F4, $A, $10, $66, $10, $33, $FF, $F5
DATACJQA1J2E71F_27: dc.b $0, $0
	even