MusID__First = 1
	enum MusID_GHZ=MusID__First,MusID_SHP,MusID_SR,MusID_DL,MusID_NT,MusID_UM,MusID_CM
	enum MusID_MR=MusID_CM+1,MusID_Baka,MusID_WWGameSel,MusID_WM,MusID_S3DBInvincible,MusID_S3DBSpecStage,MusID_S3KEndLevel
	enum MusID_MM3Title=MusID_S3KEndLevel+1,MusID_MM3Boss,MusID_SPASpecStag,MusID_AllDayLong,MusID_TFIVCountDown,MusID_DontGoOff,MusID_MetalSquad
	enum MusID_Phantom=MusID_MetalSquad+1,MusID_2PResult,MusID_EHZ,MusID_OOZ,MusID_MTZ,MusID_HTZ,MusID_CNZ
	enum MusID_DEZ=MusID_CNZ+1,MusID_MCZ,MusID_SCZ,MusID_WFZ,MusID_HPZ,MusID_Ending,MusID_ExtraLife
	enum MusID_GameOver=MusID_ExtraLife+1,MusID_Emerald,MusID_Credits,MusID_Countdown,MusID__End