; ================================================================================
; Sprite Mappings - generated by Flex 2 Sat Nov 21 2020 23:20:29 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATAABTEQA1CQSC:
	dc.w DATAABTEQA1CQSC_0-DATAABTEQA1CQSC, DATAABTEQA1CQSC_1-DATAABTEQA1CQSC
	dc.w DATAABTEQA1CQSC_2-DATAABTEQA1CQSC, DATAABTEQA1CQSC_3-DATAABTEQA1CQSC
DATAABTEQA1CQSC_0: dc.b $0, $1
	dc.b $F8, $5, $0, $24, $0, $12, $FF, $F8
DATAABTEQA1CQSC_1: dc.b $0, $1
	dc.b $F8, $5, $0, $28, $0, $14, $FF, $F8
DATAABTEQA1CQSC_2: dc.b $0, $1
	dc.b $F8, $5, $0, $2C, $0, $16, $FF, $F8
DATAABTEQA1CQSC_3: dc.b $0, $1
	dc.b $F8, $5, $0, $33, $0, $19, $FF, $F8
	even