; ================================================================================
; Sprite Mappings - generated by Flex 2 Sat Nov 21 2020 23:26:18 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATA1VN0WJZLZ83:
	dc.w DATA1VN0WJZLZ83_0-DATA1VN0WJZLZ83, DATA1VN0WJZLZ83_1-DATA1VN0WJZLZ83
	dc.w DATA1VN0WJZLZ83_2-DATA1VN0WJZLZ83, DATA1VN0WJZLZ83_3-DATA1VN0WJZLZ83
	dc.w DATA1VN0WJZLZ83_4-DATA1VN0WJZLZ83, DATA1VN0WJZLZ83_5-DATA1VN0WJZLZ83
	dc.w DATA1VN0WJZLZ83_6-DATA1VN0WJZLZ83, DATA1VN0WJZLZ83_7-DATA1VN0WJZLZ83
	dc.w DATA1VN0WJZLZ83_8-DATA1VN0WJZLZ83, DATA1VN0WJZLZ83_9-DATA1VN0WJZLZ83
	dc.w DATA1VN0WJZLZ83_A-DATA1VN0WJZLZ83
DATA1VN0WJZLZ83_0: dc.b $0, $3
	dc.b $EC, $D, $0, $0, $0, $0, $FF, $EC
	dc.b $F4, $0, $0, $8, $0, $4, $0, $C
	dc.b $FC, $E, $0, $9, $0, $4, $FF, $F4
DATA1VN0WJZLZ83_1: dc.b $0, $3
	dc.b $EC, $6, $0, $15, $0, $A, $FF, $EC
	dc.b $EC, $9, $0, $1B, $0, $D, $FF, $FC
	dc.b $FC, $A, $0, $21, $0, $10, $FF, $FC
DATA1VN0WJZLZ83_2: dc.b $0, $3
	dc.b $EC, $6, $0, $2A, $0, $15, $FF, $EC
	dc.b $EC, $9, $0, $1B, $0, $D, $FF, $FC
	dc.b $FC, $A, $0, $21, $0, $10, $FF, $FC
DATA1VN0WJZLZ83_3: dc.b $0, $4
	dc.b $EC, $6, $0, $30, $0, $18, $FF, $EC
	dc.b $EC, $9, $0, $1B, $0, $D, $FF, $FC
	dc.b $FC, $9, $0, $36, $0, $1B, $FF, $FC
	dc.b $C, $0, $0, $3C, $0, $1E, $0, $C
DATA1VN0WJZLZ83_4: dc.b $0, $3
	dc.b $F4, $D, $0, $3D, $0, $1E, $FF, $EC
	dc.b $FC, $0, $0, $20, $0, $10, $0, $C
	dc.b $4, $8, $0, $45, $0, $22, $FF, $FC
DATA1VN0WJZLZ83_5: dc.b $0, $2
	dc.b $F8, $D, $0, $48, $0, $24, $FF, $EC
	dc.b $F8, $1, $0, $50, $0, $28, $0, $C
DATA1VN0WJZLZ83_6: dc.b $0, $3
	dc.b $F8, $D, $0, $48, $0, $24, $FF, $EC
	dc.b $F8, $1, $0, $50, $0, $28, $0, $C
	dc.b $FE, $0, $0, $52, $0, $29, $0, $14
DATA1VN0WJZLZ83_7: dc.b $0, $3
	dc.b $F8, $D, $0, $48, $0, $24, $FF, $EC
	dc.b $F8, $1, $0, $50, $0, $28, $0, $C
	dc.b $FE, $4, $0, $53, $0, $29, $0, $14
DATA1VN0WJZLZ83_8: dc.b $0, $3
	dc.b $F8, $D, $0, $48, $0, $24, $FF, $EC
	dc.b $F8, $1, $0, $50, $0, $28, $0, $C
	dc.b $FE, $0, $E0, $52, $E0, $29, $0, $14
DATA1VN0WJZLZ83_9: dc.b $0, $3
	dc.b $F8, $D, $0, $48, $0, $24, $FF, $EC
	dc.b $F8, $1, $0, $50, $0, $28, $0, $C
	dc.b $FE, $4, $E0, $53, $E0, $29, $0, $14
DATA1VN0WJZLZ83_A: dc.b $0, $0
	even