; ================================================================================
; Sprite Mappings - generated by Flex 2 Fri Feb 05 2021 10:27:45 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATA61T01WTY2YN:
	dc.w DATA61T01WTY2YN_0-DATA61T01WTY2YN, DATA61T01WTY2YN_1-DATA61T01WTY2YN
	dc.w DATA61T01WTY2YN_2-DATA61T01WTY2YN, DATA61T01WTY2YN_3-DATA61T01WTY2YN
	dc.w DATA61T01WTY2YN_4-DATA61T01WTY2YN, DATA61T01WTY2YN_5-DATA61T01WTY2YN
	dc.w DATA61T01WTY2YN_6-DATA61T01WTY2YN, DATA61T01WTY2YN_7-DATA61T01WTY2YN
	dc.w DATA61T01WTY2YN_8-DATA61T01WTY2YN, DATA61T01WTY2YN_9-DATA61T01WTY2YN
	dc.w DATA61T01WTY2YN_A-DATA61T01WTY2YN, DATA61T01WTY2YN_B-DATA61T01WTY2YN
	dc.w DATA61T01WTY2YN_C-DATA61T01WTY2YN
DATA61T01WTY2YN_0: dc.b $0, $6
	dc.b $EC, $1, $0, $0, $0, $0, $FF, $E4
	dc.b $FC, $E, $20, $2, $20, $1, $FF, $E4
	dc.b $FC, $E, $20, $E, $20, $7, $0, $4
	dc.b $14, $C, $20, $1A, $20, $D, $FF, $EC
	dc.b $14, $0, $20, $1E, $20, $F, $0, $C
	dc.b $EC, $1, $0, $1F, $0, $F, $0, $14
DATA61T01WTY2YN_1: dc.b $0, $3
	dc.b $E4, $4, $0, $21, $0, $10, $FF, $F4
	dc.b $EC, $D, $0, $23, $0, $11, $FF, $EC
	dc.b $EC, $1, $0, $2B, $0, $15, $0, $C
DATA61T01WTY2YN_2: dc.b $0, $3
	dc.b $E4, $4, $0, $21, $0, $10, $FF, $F4
	dc.b $EC, $D, $0, $2D, $0, $16, $FF, $EC
	dc.b $EC, $1, $0, $2B, $0, $15, $0, $C
DATA61T01WTY2YN_3: dc.b $0, $3
	dc.b $EC, $9, $0, $35, $0, $1A, $FF, $EC
	dc.b $EC, $5, $0, $3B, $0, $1D, $0, $4
	dc.b $E4, $0, $0, $3F, $0, $1F, $FF, $FD
DATA61T01WTY2YN_4: dc.b $0, $4
	dc.b $EC, $9, $0, $40, $0, $20, $FF, $EC
	dc.b $EC, $5, $0, $46, $0, $23, $0, $4
	dc.b $E4, $0, $0, $4A, $0, $25, $FF, $F9
	dc.b $E4, $0, $8, $4A, $8, $25, $0, $1
DATA61T01WTY2YN_5: dc.b $0, $3
	dc.b $E4, $8, $0, $4B, $0, $25, $FF, $F4
	dc.b $EC, $9, $0, $4E, $0, $27, $FF, $EC
	dc.b $EC, $5, $0, $54, $0, $2A, $0, $4
DATA61T01WTY2YN_6: dc.b $0, $4
	dc.b $E4, $4, $0, $58, $0, $2C, $0, $4
	dc.b $E4, $4, $0, $21, $0, $10, $FF, $F4
	dc.b $EC, $D, $0, $2D, $0, $16, $FF, $EC
	dc.b $EC, $1, $0, $2B, $0, $15, $0, $C
DATA61T01WTY2YN_7: dc.b $0, $3
	dc.b $E4, $8, $0, $5A, $0, $2D, $FF, $F4
	dc.b $EC, $9, $0, $5D, $0, $2E, $FF, $EC
	dc.b $EC, $5, $0, $63, $0, $31, $0, $4
DATA61T01WTY2YN_8: dc.b $0, $1
	dc.b $4, $5, $0, $67, $0, $33, $0, $22
DATA61T01WTY2YN_9: dc.b $0, $1
	dc.b $4, $5, $0, $6B, $0, $35, $0, $22
DATA61T01WTY2YN_A: dc.b $0, $0
DATA61T01WTY2YN_B: dc.b $0, $2
	dc.b $0, $8, $0, $6F, $0, $37, $0, $22
	dc.b $8, $8, $10, $6F, $10, $37, $0, $22
DATA61T01WTY2YN_C: dc.b $0, $3
	dc.b $FC, $A, $0, $72, $0, $39, $0, $23
	dc.b $F4, $0, $0, $7B, $0, $3D, $0, $2B
	dc.b $FC, $1, $0, $7C, $0, $3E, $0, $3B
	even