; ================================================================================
; Sprite Mappings - generated by Flex 2 Fri Nov 27 2020 19:52:21 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATAGW3I36UH234:
	dc.w DATAGW3I36UH234_0-DATAGW3I36UH234, DATAGW3I36UH234_1-DATAGW3I36UH234
	dc.w DATAGW3I36UH234_2-DATAGW3I36UH234, DATAGW3I36UH234_3-DATAGW3I36UH234
	dc.w DATAGW3I36UH234_4-DATAGW3I36UH234, DATAGW3I36UH234_5-DATAGW3I36UH234
	dc.w DATAGW3I36UH234_6-DATAGW3I36UH234, DATAGW3I36UH234_7-DATAGW3I36UH234
	dc.w DATAGW3I36UH234_8-DATAGW3I36UH234, DATAGW3I36UH234_9-DATAGW3I36UH234
	dc.w DATAGW3I36UH234_A-DATAGW3I36UH234, DATAGW3I36UH234_B-DATAGW3I36UH234
	dc.w DATAGW3I36UH234_C-DATAGW3I36UH234
DATAGW3I36UH234_0: dc.b $0, $6
	dc.b $EC, $1, $0, $A, $0, $5, $FF, $E4
	dc.b $EC, $5, $0, $C, $0, $6, $0, $C
	dc.b $FC, $E, $20, $10, $20, $8, $FF, $E4
	dc.b $FC, $E, $20, $1C, $20, $E, $0, $4
	dc.b $14, $C, $20, $28, $20, $14, $FF, $EC
	dc.b $14, $0, $20, $2C, $20, $16, $0, $C
DATAGW3I36UH234_1: dc.b $0, $2
	dc.b $E4, $4, $0, $0, $0, $0, $FF, $F4
	dc.b $EC, $D, $0, $2, $0, $1, $FF, $EC
DATAGW3I36UH234_2: dc.b $0, $2
	dc.b $E4, $4, $0, $0, $0, $0, $FF, $F4
	dc.b $EC, $D, $0, $35, $0, $1A, $FF, $EC
DATAGW3I36UH234_3: dc.b $0, $3
	dc.b $E4, $8, $0, $3D, $0, $1E, $FF, $F4
	dc.b $EC, $9, $0, $40, $0, $20, $FF, $EC
	dc.b $EC, $5, $0, $46, $0, $23, $0, $4
DATAGW3I36UH234_4: dc.b $0, $3
	dc.b $E4, $8, $0, $4A, $0, $25, $FF, $F4
	dc.b $EC, $9, $0, $4D, $0, $26, $FF, $EC
	dc.b $EC, $5, $0, $53, $0, $29, $0, $4
DATAGW3I36UH234_5: dc.b $0, $3
	dc.b $E4, $8, $0, $6C, $0, $36, $FF, $F4
	dc.b $EC, $9, $0, $6F, $0, $37, $FF, $EC
	dc.b $EC, $5, $0, $75, $0, $3A, $0, $4
DATAGW3I36UH234_6: dc.b $0, $3
	dc.b $E4, $4, $0, $64, $0, $32, $0, $4
	dc.b $E4, $4, $0, $0, $0, $0, $FF, $F4
	dc.b $EC, $D, $0, $35, $0, $1A, $FF, $EC
DATAGW3I36UH234_7: dc.b $0, $3
	dc.b $E4, $8, $0, $57, $0, $2B, $FF, $F4
	dc.b $EC, $9, $0, $5A, $0, $2D, $FF, $EC
	dc.b $EC, $5, $0, $60, $0, $30, $0, $4
DATAGW3I36UH234_8: dc.b $0, $1
	dc.b $4, $5, $0, $2D, $0, $16, $0, $22
DATAGW3I36UH234_9: dc.b $0, $1
	dc.b $4, $5, $0, $31, $0, $18, $0, $22
DATAGW3I36UH234_A: dc.b $0, $0
DATAGW3I36UH234_B: dc.b $0, $2
	dc.b $0, $8, $1, $2A, $0, $95, $0, $22
	dc.b $8, $8, $11, $2A, $10, $95, $0, $22
DATAGW3I36UH234_C: dc.b $0, $2
	dc.b $F8, $B, $1, $2D, $0, $96, $0, $22
	dc.b $0, $1, $1, $39, $0, $9C, $0, $3A
	even