; ================================================================================
; Sprite Mappings - generated by Flex 2 Thu Nov 26 2020 22:01:25 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATAQ8Y8WY718:
	dc.w DATAQ8Y8WY718_0-DATAQ8Y8WY718, DATAQ8Y8WY718_1-DATAQ8Y8WY718
	dc.w DATAQ8Y8WY718_2-DATAQ8Y8WY718
DATAQ8Y8WY718_0: dc.b $0, $2
	dc.b $F8, $9, $0, $4, $0, $2, $FF, $E8
	dc.b $F8, $9, $0, $4, $0, $2, $0, $0
DATAQ8Y8WY718_1: dc.b $0, $1
	dc.b $F8, $5, $0, $0, $0, $0, $FF, $F8
DATAQ8Y8WY718_2: dc.b $0, $1
	dc.b $F8, $5, $0, $A, $0, $5, $FF, $F8
	even