; ================================================================================
; Sprite Mappings - generated by Flex 2 Fri Oct 23 2020 09:00:12 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATA5WEGL9JV8ZS:
	dc.w DATA5WEGL9JV8ZS_0-DATA5WEGL9JV8ZS, DATA5WEGL9JV8ZS_1-DATA5WEGL9JV8ZS
	dc.w DATA5WEGL9JV8ZS_2-DATA5WEGL9JV8ZS, DATA5WEGL9JV8ZS_3-DATA5WEGL9JV8ZS
	dc.w DATA5WEGL9JV8ZS_4-DATA5WEGL9JV8ZS, DATA5WEGL9JV8ZS_5-DATA5WEGL9JV8ZS
	dc.w DATA5WEGL9JV8ZS_6-DATA5WEGL9JV8ZS, DATA5WEGL9JV8ZS_7-DATA5WEGL9JV8ZS
DATA5WEGL9JV8ZS_0: dc.b $1
	dc.b $F8, $5, $20, $0, $F8
DATA5WEGL9JV8ZS_1: dc.b $1
	dc.b $F8, $5, $20, $4, $F8
DATA5WEGL9JV8ZS_2: dc.b $1
	dc.b $F8, $1, $20, $8, $FC
DATA5WEGL9JV8ZS_3: dc.b $1
	dc.b $F8, $5, $28, $4, $F8
DATA5WEGL9JV8ZS_4: dc.b $1
	dc.b $F8, $5, $20, $A, $F8
DATA5WEGL9JV8ZS_5: dc.b $1
	dc.b $F8, $5, $38, $A, $F8
DATA5WEGL9JV8ZS_6: dc.b $1
	dc.b $F8, $5, $28, $A, $F8
DATA5WEGL9JV8ZS_7: dc.b $1
	dc.b $F8, $5, $30, $A, $F8
	even