; ================================================================================
; Sprite Mappings - generated by Flex 2 Sun Oct 18 2020 19:04:52 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAUFDWO34PL3:
	dc.w DATAUFDWO34PL3_0-DATAUFDWO34PL3, DATAUFDWO34PL3_1-DATAUFDWO34PL3
	dc.w DATAUFDWO34PL3_2-DATAUFDWO34PL3, DATAUFDWO34PL3_3-DATAUFDWO34PL3
	dc.w DATAUFDWO34PL3_4-DATAUFDWO34PL3, DATAUFDWO34PL3_5-DATAUFDWO34PL3
	dc.w DATAUFDWO34PL3_6-DATAUFDWO34PL3, DATAUFDWO34PL3_7-DATAUFDWO34PL3
	dc.w DATAUFDWO34PL3_8-DATAUFDWO34PL3
DATAUFDWO34PL3_0: dc.b $0, $D
	dc.b $F8, $5, $0, $8, $0, $4, $FF, $90
	dc.b $F8, $5, $0, $1C, $0, $E, $FF, $A0
	dc.b $F8, $5, $0, $0, $0, $0, $FF, $B0
	dc.b $F8, $5, $0, $32, $0, $19, $FF, $C0
	dc.b $F8, $5, $0, $3E, $0, $1F, $FF, $D0
	dc.b $F8, $5, $0, $10, $0, $8, $FF, $F0
	dc.b $F8, $5, $0, $2A, $0, $15, $0, $0
	dc.b $F8, $5, $0, $10, $0, $8, $0, $10
	dc.b $F8, $5, $0, $3A, $0, $1D, $0, $20
	dc.b $F8, $5, $0, $0, $0, $0, $0, $30
	dc.b $F8, $5, $0, $26, $0, $13, $0, $40
	dc.b $F8, $5, $0, $C, $0, $6, $0, $50
	dc.b $F8, $5, $0, $3E, $0, $1F, $0, $60
DATAUFDWO34PL3_1: dc.b $0, $6
	dc.b $F8, $D, $21, $4A, $20, $A5, $FF, $B0
	dc.b $F8, $1, $21, $62, $20, $B1, $FF, $D0
	dc.b $F8, $9, $1, $64, $0, $B2, $0, $18
	dc.b $F8, $D, $1, $6A, $0, $B5, $0, $30
	dc.b $F7, $4, $0, $6E, $0, $37, $FF, $CD
	dc.b $FF, $4, $18, $6E, $18, $37, $FF, $CD
DATAUFDWO34PL3_2: dc.b $0, $7
	dc.b $F8, $D, $21, $52, $20, $A9, $FF, $B0
	dc.b $F8, $D, $20, $66, $20, $33, $FF, $D9
	dc.b $F8, $1, $21, $4A, $20, $A5, $FF, $F9
	dc.b $F7, $4, $0, $6E, $0, $37, $FF, $F6
	dc.b $FF, $4, $18, $6E, $18, $37, $FF, $F6
	dc.b $F8, $D, $FF, $F8, $FB, $FC, $0, $28
	dc.b $F8, $1, $1, $70, $0, $B8, $0, $48
DATAUFDWO34PL3_3: dc.b $0, $0
DATAUFDWO34PL3_4: dc.b $0, $4
	dc.b $F8, $D, $9F, $D1, $9B, $E8, $FF, $B0
	dc.b $F8, $D, $9F, $D9, $9B, $EC, $FF, $D0
	dc.b $F8, $1, $9F, $E1, $9B, $F0, $FF, $F0
	dc.b $F8, $6, $1F, $E3, $1B, $F1, $0, $40
DATAUFDWO34PL3_5: dc.b $0, $4
	dc.b $F8, $D, $9F, $D1, $9B, $E8, $FF, $B0
	dc.b $F8, $D, $9F, $D9, $9B, $EC, $FF, $D0
	dc.b $F8, $1, $9F, $E1, $9B, $F0, $FF, $F0
	dc.b $F8, $6, $1F, $E9, $1B, $F4, $0, $40
DATAUFDWO34PL3_6: dc.b $0, $3
	dc.b $F8, $D, $9F, $D1, $9B, $E8, $FF, $B0
	dc.b $F8, $D, $9F, $D9, $9B, $EC, $FF, $D0
	dc.b $F8, $1, $9F, $E1, $9B, $F0, $FF, $F0
DATAUFDWO34PL3_7: dc.b $0, $C
	dc.b $F8, $5, $0, $3E, $0, $1F, $FF, $9C
	dc.b $F8, $5, $0, $36, $0, $1B, $FF, $AC
	dc.b $F8, $5, $0, $10, $0, $8, $FF, $BC
	dc.b $F8, $5, $0, $8, $0, $4, $FF, $CC
	dc.b $F8, $1, $0, $20, $0, $10, $FF, $DC
	dc.b $F8, $5, $0, $0, $0, $0, $FF, $E4
	dc.b $F8, $5, $0, $26, $0, $13, $FF, $F4
	dc.b $F8, $5, $0, $3E, $0, $1F, $0, $14
	dc.b $F8, $5, $0, $42, $0, $21, $0, $24
	dc.b $F8, $5, $0, $0, $0, $0, $0, $34
	dc.b $F8, $5, $0, $18, $0, $C, $0, $44
	dc.b $F8, $5, $0, $10, $0, $8, $0, $54
DATAUFDWO34PL3_8: dc.b $0, $F
	dc.b $F8, $5, $0, $3E, $0, $1F, $FF, $88
	dc.b $F8, $5, $0, $32, $0, $19, $FF, $98
	dc.b $F8, $5, $0, $2E, $0, $17, $FF, $A8
	dc.b $F8, $1, $0, $20, $0, $10, $FF, $B8
	dc.b $F8, $5, $0, $8, $0, $4, $FF, $C0
	dc.b $F8, $5, $0, $18, $0, $C, $FF, $D8
	dc.b $F8, $5, $0, $32, $0, $19, $FF, $E8
	dc.b $F8, $5, $0, $42, $0, $21, $FF, $F8
	dc.b $F8, $5, $0, $42, $0, $21, $0, $10
	dc.b $F8, $5, $0, $1C, $0, $E, $0, $20
	dc.b $F8, $5, $0, $10, $0, $8, $0, $30
	dc.b $F8, $5, $0, $2A, $0, $15, $0, $40
	dc.b $F8, $5, $0, $0, $0, $0, $0, $58
	dc.b $F8, $5, $0, $26, $0, $13, $0, $68
	dc.b $F8, $5, $0, $26, $0, $13, $0, $78
	even